### ISSUE TITLE
Optimizations using changelists and ThreadPool (or asyncio)

### ISSUE THREAD

**Issue by TheDJVG** [octodns/octodns-edgedns#38]
Hello,

### Changelists
While working on integrating our existing Akamai EdgeDNS zone with octoDNS I noticed that the time it takes to make the changes can be significant (mainly because we make large changes). I've observed the following:

1. When a normal record is added/changed it goes through the [recordset API](https://techdocs.akamai.com/edge-dns/reference/post-zones-zone-names-name-types-type). Depending on your location this API response can take some time before the next record is processed.
2. Every change creates a history entry that needs to be processed (although I don't know exactly how it works on the Akamai side as only the "latest" gets a value for "Activation time".

As I was curious to see if the use of [changelists](https://techdocs.akamai.com/edge-dns/reference/get-changelists) (more or less staging changes to be committed) is faster, and it is.

Based on a couple of runs (adding 100 records) it would take between 60 and 70 seconds to complete while using the changelist is between 40 and 50 seconds (create new changelist, add 100 records to the changelist, commit changelist).

### ThreadPool (or asyncio)
At the same time I was wondering if we could parallelize these requests using a ThreadPool executor.
Having experimented with it (and using 10 workers, and still the same 100 records) I've observed a ~%50 decrease in time spend on making the changes. 10 seconds when doing it normal (the recordset API) and 5 seconds using the changelist API.

Additionally having the changes you wanna make in a single history event inside the Akamai EdgeDNS API/dashboard might help with better observability over the changes made instead of creating a history event for every single change.

### Questions

I'm happy to work on this as we would like these features available to speed up our change deployment but I have a couple of questions:

1. Should we use a ThreadPoolExecutor (already used by the manager/plan) or go the `asyncio` path? 
2. What would be a sane amount of workers to default to when enabled, 2? I've tested with 10 workers without problems.
3. Should we turn the use of changelists in a separate provider or is simply making it configurable enough?

Thanks for your time!

Daan

**Comment by ross** [comment]
> 3\. Should we turn the use of changelists in a separate provider or is simply making it configurable enough?

I'm not directly familiar with Akamai EdgeDNS, but if changelists are an option they'd almost certainly be the way to go. Specifically from a safety standpoint. If they speed things up that'd be an added benefit. 

Having grouped changes that ostensibly happen atomically is safer than one-by-one changes since it ensures that related modifications happen in one go to the degree possible. An example of when this can matter would be changing an `A` to a `CNAME` of vice versa. In providers that don't have a changeset/batch API (pretty much all of them) there's at least a small amount of time when the old record has been deleted before the new one has been created. This in theory can allow for a gap in DNS lookups. Worse case things can fail between the delete and add and end up with no record at the node for a much longer time.

Route53Provider in octodns-route53 is the only current provider (that I know of) that has a batch style API. Everything else is one-by-one (the archived octodns-dyn did too.) With it there's a limit on the batch size so even that doesn't ensure safety, but under normal circumstances it's there.

> * Should we use a ThreadPoolExecutor (already used by the manager/plan) or go the `asyncio` path?

IF any sort of async stuff showed up in the provider it would probably need to stick w/`ThreadPoolExecutor` since it's in use elsewhere and mixing async approaches in a single "app" would at best be a mess to debug and more likely break things.

**Comment by TheDJVG** [comment]
Attached a patch to use the changelist feature (unable to commit from work laptop and I don't have access the Akamai API outside of office). It's missing tests currently but existing non-changelist test should succeed.

Here an example to show that the changes were all part of 1 version:
<img width="1015" alt="image" src="https://github.com/octodns/octodns-edgedns/assets/17107225/66ea6dd2-3309-4a23-be48-de41295fb7f4">

Patch: [38-use-changelist.patch](https://github.com/octodns/octodns-edgedns/files/14444537/38-use-changelist.patch)

**Comment by ross** [comment]
After a bit of a delay to get https://github.com/octodns/octodns-edgedns/pull/40 sorted I created a PR with the patch. Further discussion/changes should happen over there.

**Comment by ross** [comment]
> Regarding the ThreadPoolExecutor I have mixed results. The main problem seems to be that while it seem the change has been received (I get a HTTP 204) it's not actually applied when the changelist is submitted. I will do some more work with dumping the change list before submitting to see if the change is actually in there.

Their API probably has eventual consistency properties. Probably best to hold off on the `ThreadPoolExecutor` stuff anyway and see if it's absolutely necessary after the changelists stuff is in place. It's an extra complication that would be best avoided if at all possible.
